---
- copy: src=config/sysctl-network.conf dest=/etc/sysctl.d/network.conf
- copy: src=config/interfaces dest=/etc/network/interfaces
- copy: src=initscripts/firewall dest=/etc/init.d/
  notify: restart firewall
- copy: src=initscripts/firewall6 dest=/etc/init.d/
  notify: restart firewall
- service: name=firewall enabled=true
- service: name=firewall6 enabled=true

- apt: pkg=isc-dhcp-server
- copy: src=config/dhcpd.conf dest=/etc/dhcp/dhcpd.conf
  notify: restart dhcp

- apt: pkg=bind9,resolvconf
- copy: src=config/bind/ dest=/etc/bind/
  notify: restart bind
- copy: src=config/default-bind dest=/etc/default/bind9 
  notify: restart bind
- copy: src=config/resolv.conf.tail dest=/etc/resolvconf/resolv.conf.d/tail
  notify: restart resolvconf

- apt: pkg=openvpn
- copy: src=config/openvpn-www.conf dest=/etc/openvpn/
- copy: src=secret/openvpn/ dest=/etc/openvpn/

- copy: src=secret/ssh/ dest=/etc/ssh/
  notify: restart sshd
- copy: src=config/sshd_config dest=/etc/ssh/sshd_config
  notify: restart sshd
